# CMake generated Testfile for 
# Source directory: /mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4
# Build directory: /mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(RectangleTester.constructorOfRectangleStartingInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=RectangleTester.constructorOfRectangleStartingInBeginningOfCoordinateSystem")
set_tests_properties(RectangleTester.constructorOfRectangleStartingInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(RectangleTester.isInMethodOfRectangleStartingInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=RectangleTester.isInMethodOfRectangleStartingInBeginningOfCoordinateSystem")
set_tests_properties(RectangleTester.isInMethodOfRectangleStartingInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(RectangleTester.isInMethodOfRectangleStartingNotInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=RectangleTester.isInMethodOfRectangleStartingNotInBeginningOfCoordinateSystem")
set_tests_properties(RectangleTester.isInMethodOfRectangleStartingNotInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(CircleTester.constructorOfCircleStartingInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=CircleTester.constructorOfCircleStartingInBeginningOfCoordinateSystem")
set_tests_properties(CircleTester.constructorOfCircleStartingInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(CircleTester.isInMethodOfCircleStartingInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=CircleTester.isInMethodOfCircleStartingInBeginningOfCoordinateSystem")
set_tests_properties(CircleTester.isInMethodOfCircleStartingInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(CircleTester.isInMethodOfCircleStartingNotInBeginningOfCoordinateSystem "ShapesTests" "--gtest_filter=CircleTester.isInMethodOfCircleStartingNotInBeginningOfCoordinateSystem")
set_tests_properties(CircleTester.isInMethodOfCircleStartingNotInBeginningOfCoordinateSystem PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(ShapeCompositeTester.sumOfSqhareAndCircle "ShapesTests" "--gtest_filter=ShapeCompositeTester.sumOfSqhareAndCircle")
set_tests_properties(ShapeCompositeTester.sumOfSqhareAndCircle PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(ShapeCompositeTester.intersectionOfSqhareAndCircle "ShapesTests" "--gtest_filter=ShapeCompositeTester.intersectionOfSqhareAndCircle")
set_tests_properties(ShapeCompositeTester.intersectionOfSqhareAndCircle PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(ShapeCompositeTester.differenceOfSqhareAndCircle "ShapesTests" "--gtest_filter=ShapeCompositeTester.differenceOfSqhareAndCircle")
set_tests_properties(ShapeCompositeTester.differenceOfSqhareAndCircle PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(ShapeCompositeTester.drawingHouse "ShapesTests" "--gtest_filter=ShapeCompositeTester.drawingHouse")
set_tests_properties(ShapeCompositeTester.drawingHouse PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;29;GTEST_ADD_TESTS;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
add_test(lab_test "lab")
set_tests_properties(lab_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;31;add_test;/mnt/c/Users/KUBa/Downloads/zaj4ShapeDrawing_dlaStudentow/src/lab4/CMakeLists.txt;0;")
